#pragma once
typedef enum TOKEN_KEYWORDS{
    TOKEN_ARROW,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_COMMA,
    TOKEN_COLON,
    TOKEN_QUOTE,
    TOKEN_IF,
    TOKEN_ALL,
    TOKEN_IN,
    TOKEN_FOR,
    TOKEN_FROM,
    TOKEN_PREPARE,
    TOKEN_REQUEST,
    TOKEN_ANALYZE,
    TOKEN_SEND,
    TOKEN_CONTENT,
    TOKEN_TYPE,
    TOKEN_LENGTH,
    TOKEN_TO,
    TOKEN_SCHEME,
    TOKEN_STATUS,
    TOKEN_CODE,
    TOKEN_HEADERS,
    TOKEN_METHOD,
    TOKEN_AVAILABLE,
    TOKEN_BODY,
    TOKEN_CONNECTION,
    TOKEN_LANGUAGES,
    TOKEN_USER_AGENT,
    TOKEN_SPACE_KEY,
    TOKEN_HOST,
    TOKEN_HTTP,
    TOKEN_HTTPS,
    TOKEN_EXTRACT,
    TOKEN_EOF,
    TOKEN_UNKNOWN,
    TOKEN_STRING

}TOKEN_KEYWORDS;

typedef struct{
    char* value;
    TOKEN_KEYWORDS TokenType;    
}tokens;
